language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_dacd01900361_key -iv $encrypted_dacd01900361_iv -in .id_rsa.enc -out .id_rsa -d
  - sudo add-apt-repository -y ppa:dan-witt/gstreamer
  - sudo apt-get -qq update
  - sudo apt-get install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
deploy:
  provider: script
  script: bash travis_deploy.sh
  on:
    branch: master

