language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"

before_install:
  - sudo add-apt-repository ppa:dan-witt/gstreamer
  - sudo apt-get -qq update
  - sudo apt-get install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev