version: "3.3"
services:
  app-endpoint-server:
    build:
      context: ../../
      dockerfile: app-endpoint-server/Dockerfile
    volumes:
      - x11temp:/tmp/.X11-unix
      - nvidia_driver:/usr/local/nvidia/lib64:ro
    ports:
      - '8081:8081'
    environment:
      DISPLAY: ':0'
      XDG_RUNTIME_DIR: '/tmp'
    devices:
      - /dev/nvidia0
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools

  xnvidia:
    privileged: true
    build:
      context: .
      dockerfile: xnvidia.dockerfile
    volumes:
      - x11temp:/tmp/.X11-unix
      - nvidia_driver:/usr/local/nvidia/lib64:ro
    devices:
      - /dev/nvidia0
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools

volumes:
  x11temp:
  nvidia_driver:
    driver: local
    driver_opts:
     type: none
     o: bind
     device: "/var/lib/nvidia/lib64"