version: "3.3"
services:
  app-endpoint-server:
    build:
      context: ../../
      dockerfile: app-endpoint-server/Dockerfile
    volumes:
      - x11temp:/tmp/.X11-unix
    ports:
      - '8081:8081'
    environment:
      DISPLAY: ':0'
      XDG_RUNTIME_DIR: '/tmp'
#      GST_DEBUG: '3'
  xdummy:
    build:
      context: containers/xdummy
      dockerfile: xdummy.dockerfile
    volumes:
      - x11temp:/tmp/.X11-unix
volumes:
  x11temp: